---
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: v1
kind: Namespace
metadata:
  name: busybox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echoserver
          image: k8s.gcr.io/e2e-test-images/echoserver:2.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: web
          resources:
            requests:
              memory: 64Mi
              cpu: 300m
            limits:
              memory: 64Mi
              cpu: 400m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  namespace: busybox
  labels:
    app: busybox1
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "360000"
      imagePullPolicy: IfNotPresent
      name: busybox
      resources:
        requests:
          memory: 64Mi
          cpu: 300m
        limits:
          memory: 64Mi
          cpu: 400m
  restartPolicy: Always
  