name: Build - Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install libpcap-dev
        run: sudo apt install -y libpcap-dev
    
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'
      
      - name: Install dependencies
        run: go get .

      - name: Test
        run: go test -v ./... --race

      - name: Build
        run: go build -v ./...
